[site]
title = "Ruhan Wang"
description = "PhD Candidate at Indiana University."
favicon = "/favicon.svg"
last_updated = "May 9, 2026"

[author]
name = "Ruhan Wang / 王汝涵"
title = "PhD Candidate"
institution = "Indiana University"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "ruhwang@iu.edu"
location = "Bloomington, United States"
location_url = "https://maps.google.com"
location_details = [
  "Room 3061J, Luddy School of Informatics, Computing, and Engineering,",
  "700 N Woodlawn Ave, Bloomington, IN 47408"
]
google_scholar = "https://scholar.google.com/citations?user=vHgJIPoAAAAJ&hl=en"
github = "https://github.com/Ruhan-Wang"
linkedin = "https://www.linkedin.com/in/ruhan-wang-075922255/"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = false
locales = ["en"]
default_locale = "en"
mode = "fixed"
fixed_locale = "en"
persist = false
switcher = false

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Teaching"
type = "page"
target = "teaching"
href = "/teaching"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
